import Head from 'next/head';
import {SessionProvider} from 'next-auth/react'
import '../styles/globals.css';

const App = ({ Component, pageProps: {session, ...pageProps} }) => {
	return (
		<SessionProvider session={session}>
			<Head>
				<title>FF Adviser</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<Component {...pageProps} />
		</SessionProvider>
	);
};

export default App;
