import { Provider } from 'react-redux';
import { wrapper } from '@/store';
import Head from 'next/head';
import Nav from '../../components/Nav';
import '@/styles/globals.css';

const App = ({ Component, ...rest }) => {
	const { store, props } = wrapper.useWrappedStore(rest);
	const { pageProps } = props;

	return (
		<Provider store={store}>
			<Head>
				<title>NFL Fantasy</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>

			<Nav />
			<Component {...pageProps} />
		</Provider>
	);
};

export default App;
